### PR TITLE
Update for 0.16

### PR DESCRIPTION
**Pull request by DjSni**
Tested and it working.

### CODE REVIEW

**Comment by hertzg** [comment]
Thats it?!
Just needed to add `icon_size` field to prototypes?

Well done!

**Comment by DjSni** [comment]
Yes that´s it :)

**Comment by hertzg** [comment]
Can confirm.

Works like a charm!

**Comment by emperorjimmy** [comment]
Thanks for the fix DjSni, unfortunately I already uploaded the same work before I checked here, lol, will have to remember github in future. ;)

**Comment by DjSni** [comment]
You are welcome! I am happy to help you.

**Pull request merged**
