### PR TITLE
Update to 2.0.x

### PR DESCRIPTION
**Pull request by Vadimvr**
Updated to 2.0.x:
internal item names.
technology names.
recipe where it was "Rocket control unit" ( 1x Rocket control unit => 1x Processing unit and 1x Speed module)

### CODE REVIEW

**Review by GCoder002 — APPROVED** [review]

**Review by GCoder002 — APPROVED** [review]

**Comment by GCoder002** [comment]
Code looks fine :3

**Review by stadler0 — APPROVED** [review]
Tested. No problems

**Comment by FJSAGS** [comment]
works

**Review by emperorjimmy — COMMENTED** [review]
Seems good, merging into main branch, thanks for updating in my absence.

**Pull request merged**
